MIN_FACE_AREA_RATIO = 0.0001
MIN_MEAN_BRIGHTNESS = 50
REQUIRED_LANDMARKS = 5

MAX_MISSING_FRAMES = 10
UNCONFIRMED_MAX_MISSING_FRAMES = 2
IOU_MATCH_THRESHOLD = 0.2
PERSON_IOU_MATCH_THRESHOLD = 0.15
PERSON_DUPLICATE_IOU_THRESHOLD = 0.25
OCCLUSION_IOU_THRESHOLD = 0.12
FRAME_EDGE_MARGIN = 3

RECOGNITION_THRESHOLD = 0.65
PERSON_RECOGNITION_THRESHOLD = 0.78
FUSED_RECOGNITION_THRESHOLD = 0.60
FACE_ONLY_RECOGNITION_THRESHOLD = 0.78

FACE_SCORE_WEIGHT = 0.6
PERSON_SCORE_WEIGHT = 0.4

PERSON_DETECTOR_CONF = 0.35
PERSON_DETECTOR_MODEL = "yolov10l.pt"
PERSON_REID_MODEL = "osnet_x1_0"
MAX_EMBEDDINGS_PER_IDENTITY = 25
